version: 2.1

executors:
  dev_executor:
    docker:
      # サンプル故に，便宜上docker hubに"公開"したものをbase imageとした．
      # 基本的には，ECRやdocker hubのprivateで使用することを想定
      - image: ababa893/mlops_env_sample_ml_base:latest
  
jobs:
  initial_job:
    executor: dev_executor
    working_directory: ~/sagemaker_mlops_demo/
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
  unittests_kaggle_logistic:
    executor: dev_executor
    working_directory: ~/sagemaker_mlops_demo/
    steps:
      - checkout
      - run:
          name: add gitpython package
          command: |
            cd /opt/program
            poetry add gitpython
      - run:
          name: unittest
          command: |
            cd custom_algorithms/kaggle_titanic/logistic_regression/container/api/apps
            pytest -vv -s tests/

workflows:
  dev_build_and_deploy_and_test_api:
    jobs:
      - initial_job:
          # context: sagemaker-dev-aws-key
          filters:
            branches:
              only:
                - /feature.*/
                # - master
                # - /test-env.*/
                # - /stg-env.*/
      - unittests_kaggle_logistic:
          # context: sagemaker-dev-aws-key
          requires:
            - initial_job
          filters:
            branches:
              only:
                - /feature.*/
                # - master
                # - /test-env.*/
                # - /stg-env.*/
