version: 2.1

executors:
  dev_executor:
    docker:
      - image: debian:stretch
  
jobs:
  initial_job:
    executor: dev_executor
    working_directory: ~/sagemaker_mlops_demo/
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date


workflows:
  dev_build_and_deploy_and_test_api:
    jobs:
      - initial_job:
          # context: sagemaker-dev-aws-key
          filters:
            branches:
              only:
                - /feature.*/
                # - master
                # - /test-env.*/